// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnwbbemvpydtawgyyrfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ud2JiZW12cHlkdGF3Z3l5cmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTI2NzksImV4cCI6MjA2ODI2ODY3OX0.fi1pxKsjRpHxwMkSOXoIIe1zqAr7A6M-rxI1-2-e3Lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});